language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"

install:
   - pip install --upgrade pip
   - pip install poetry
   - poetry install -v

script:
  - poetry run task test

after_success:
  - pipenv run codecov
